export const CLEAR_FILTER = 'CLEAR_FILTER';
export const FETCH_EARTHQUAKES = 'FETCH_EARTHQUAKES';
export const EARTHQUAKES_SEARCH_RESULTS_SUCCESS = 'EARTHQUAKES_SEARCH_RESULTS_SUCCESS';
export const EARTHQUAKE_SEARCH_RESULTS_FAILURE = 'EARTHQUAKES_SEARCH_RESULTS_FAILURE';

export const SET_EARTHQUAKE_MAGNITUDE_TYPE_FILTER = 'SET_EARTHQUAKE_MAGINTUDE_TYPE_FILTER';
export const SET_EARTHQUAKE_MAGNITUDE_NB_FILTER = 'SET_EARTHQUAKE_MAGINTUDE_NB_FILTER';
export const UNSET_EARTHQUAKE_MAGNITUDE_NB_FILTER = 'UNSET_EARTHQUAKE_MAGNITUDE_NB_FILTER';